### ISSUE TITLE
No doorbell press property

### ISSUE THREAD

**Issue by dkoppenh** [damooooooooooh/ring-adapter#8]
I have a Ring Video Doorbell 3 Plus, but don't see a property for a doorbell button press. Motion, battery percent, and low battery status are there, but nothing for the doorbell itself.

I'm guessing my deviceKind isn't accounted for?

Thanks,
David

**Comment by damooooooooooh** [comment]
Hi there, I'll realise an update today which should resolve this.

**Comment by damooooooooooh** [comment]
I've issued a pull request to the main addon list.  When merged, you should have v9 that should resolve the issue.  Let me know if it resolves.

**Comment by damooooooooooh** [comment]
Pending pull request on Webthings Addon list.  
https://github.com/WebThingsIO/addon-list/pull/1462

**Comment by damooooooooooh** [comment]
Still pending the pull request to the addon library.  If you are technical I can send details on how to manually install the updated adapter.

**Comment by dkoppenh** [comment]
I'm technical enough. I'd appreciate learning how to manually install the updated adapter.

**Comment by damooooooooooh** [comment]
Do not delete the adapter on the Webthings User Interface.
You can follow the below process to install the updated adapter manually.
It is simple, but you do so at your own risk.

ssh onto the pi, then:

goto the addon directory
`cd /home/pi/.webthings/addons/`

delete the existing ring-adapter directory 

download the latest adapter from github
`wget https://github.com/damooooooooooh/ring-adapter/releases/download/v0.0.9/ring-adapter-0.0.9.tgz`

unpack the tar file
`tar -xvf ring-adapter-0.0.9.tgz`

rename the unpacked directory from package to ring-adapter
`mv package ring-adapter`

Finally stop and then start the adapter on the webthings GUI and you should now have the pushbutton property and associated events.

**Comment by dkoppenh** [comment]
Awesome, thank you!

I had to change & add a few steps since I'm running the webthings-gateway docker image, but in the end, I'm running 0.0.9, complete with the ding property.

**Comment by damooooooooooh** [comment]
Closed with Pull request https://github.com/WebThingsIO/addon-list/pull/1462
